#! /usr/local/bin/python3
import sys
import subprocess as subp

def getip():
  print((subp.getoutput('ifconfig en0 inet').split('\n'))[1].lstrip().split(' ')[1])


if (__name__ == "__main__"):
  getip()
