#! /usr/local/bin/python3
import subprocess
import argparse

def updateEveryting(python, conda, vim, zsh, gem, brew, ycm, explicit, clean):
    if not (python or brew or conda or vim or vim or explicit):
        subprocess.run( 'brew update && brew upgrade', shell=True )
        subprocess.run( "pip3 freeze --all | sed 's/==.*//g' | pip3 install -U -r /dev/stdin", shell=True )
        subprocess.run( 'conda upgrade -y --all', shell=True )
        subprocess.run( 'vim +PluginUpdate +qall', shell=True )
        subprocess.run( 'env ZSH=$ZSH sh $ZSH/tools/upgrade.sh', shell=True )
    if brew:
        subprocess.run( 'brew update && brew upgrade', shell=True )
    if python:
        #a fire and forget method to update everything you have installed through pip
        subprocess.run( r"pip3 freeze --all | sed 's/==.*//g' | pip3 install -U -r /dev/stdin", shell=True )
    if conda:
        subprocess.run( 'conda upgrade -y --all', shell=True )
    if vim:
        subprocess.run( 'vim +PluginUpdate +qall', shell=True )
    if zsh:
        subprocess.run( 'env ZSH=$ZSH sh $ZSH/tools/upgrade.sh', shell=True )
    if gem:
        subprocess.run( 'gem update', shell=True )
    if ycm:
        subprocess.run( 'python3 ~/.vim/bundle/YouCompleteMe/install.py', shell=True )
    if clean:
        subprocess.run( 'brew cleanup && brew cask cleanup; gem cleanup', shell=True)

parser = argparse.ArgumentParser(description = 'Updates system package managers. With no arguments pip3, conda, vim plugins, oh_my_zsh and homebrew will be updated. Called with arguments only the given package managers will be updated. With the exception of gem. Running with no flags is equivalent to update-everything -pcvbz.')
parser.add_argument('--python', '-p', action='store_true', help = 'Update all pip3 packages.')
parser.add_argument('--conda', '-c', action='store_true', help = 'Update all conda packages, no confirmation.')
parser.add_argument('--vim', '-v', action='store_true', help = 'Update all vundle plugins.')
parser.add_argument('--brew', '-b', action='store_true', help = 'Update all homebrew packages.')
parser.add_argument('--zsh', '-z', action='store_true', help = 'Update Oh My ZSH.')
parser.add_argument('--gem', '-g', action='store_true', help = 'Update ruby gems.')
parser.add_argument('--ycm', '-y', action='store_true', help = 'Recompile the YouCompleteMe vim plugin.')
parser.add_argument('--explicit', '-e', action='store_true', help = 'Only update package managers passed explicitly by flag.')
parser.add_argument('--clean', action='store_true', help= 'Cleanup caches, unused or intermediate files. Used in the obvious way in brew and gem commands.')

args = parser.parse_args()

updateEveryting(args.python, args.conda, args.vim, args.zsh, args.gem, args.brew, args.ycm, args.explicit, args.clean)
